# Generated by Django 2.0 on 2018-01-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_kosh', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userpic',
            field=models.TextField(default='/static/app/userpic.png'),
        ),
    ]
