# Generated by Django 2.0 on 2018-01-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_kosh', '0003_profile_userpic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('question_id', models.IntegerField()),
            ],
        ),
    ]
