# Generated by Django 2.0.1 on 2018-01-23 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask_kosh', '0004_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('text', models.TextField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='question_id',
        ),
        migrations.AddField(
            model_name='tag',
            name='question',
            field=models.ManyToManyField(to='ask_kosh.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='correсt_question',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ask_kosh.Answer'),
        ),
    ]
